{
    extends:
        [
            'stylelint-config-standard',
            'stylelint-config-prettier',
            'stylelint-prettier/recommended',
        ],

    rules:
        {
            'selector-class-pattern': null,
            'font-family-no-missing-generic-family-keyword': null,
        },
}
